workflows:
  version: 2.1
  node-multi-build:
    jobs:
      - node-v10
      - node-v12
      - node-v14
      - node-v16:
          run_coveralls: true
      - node-v17
      - solidity-solcjs-ext-test

version: 2.1

commands:
  show-npm-version:
    steps:
      - run:
          name: Versions
          command: npm version

jobs:
  node-base: &node-base
    working_directory: ~/solc-js
    docker:
      - image: circleci/node
    parameters:
      run_coveralls:
        type: boolean
        default: false
    steps:
      - show-npm-version
      - checkout
      - restore_cache:
          key: dependency-cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: npm install
      - run:
          name: updateBinary
          command: npm run updateBinary
      - run:
          name: test
          command: npm run test
      - when:
          condition: <<parameters.run_coveralls>>
          steps:
            - run:
                name: coveralls
                command: npm run coveralls
      - save_cache:
          key: dependency-cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules

  solidity-solcjs-ext-test:
    docker:
      - image: circleci/node
    steps:
      - show-npm-version
      - checkout:
          path: solc-js/
      - run: git clone --depth 1 "https://github.com/ethereum/solidity" solidity/
      - run: cd solidity/ && curl "https://binaries.soliditylang.org/bin/soljson-nightly.js" --location --output soljson.js
      - run: cd solidity/ && test/externalTests/solc-js/solc-js.sh "$(realpath soljson.js)" "$(scripts/get_version.sh)" "$(realpath ../solc-js/)"

  node-v10:
    <<: *node-base
    docker:
      - image: circleci/node:10
  node-v12:
    <<: *node-base
    docker:
      - image: circleci/node:12
  node-v14:
    <<: *node-base
    docker:
      - image: circleci/node:14
  node-v16:
    <<: *node-base
    docker:
      - image: circleci/node:16
  node-v17:
    <<: *node-base
    docker:
      - image: circleci/node:17
